language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - 10

jobs:
  include:
    - stage: test
      script:
       - cd src 
       - npm ci && npm run lint
    - stage: build
      script:
       - cd src 
       - npm ci && npm run build
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        cleanup: false
        script: 
          - cd src 
          - npx semantic-release
        on:
          branch:    
            only:      
              - master 
              - next
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
